# accelerate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 4
num_machines: 1
machine_rank: 0
main_process_ip: null
main_process_port: null
deepspeed_config:
  deepspeed_config_file: /root/lg/Flow_RL_luogan/my_llama3_full_finetune/configs/deepspeed_config_z2.json
  zero3_init_flag: false  # ZeRO-2 不需要这个标志
use_cpu: false