# accelerate_config.yaml
compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 8
num_machines: 1
machine_rank: 0
main_process_ip: null
main_process_port: null
deepspeed_config:
  deepspeed_config_file: /nas/ganluo/Flow_RL/my_llama3_h100_new/configs/deepspeed_config_z3.json
  zero3_init_flag: true
use_cpu: false