import asyncio
import aiohttp
import json
import os
import time
from typing import List, Dict, Any, Optional
from concurrent.futures import ThreadPoolExecutor


class SimpleRewardModel4Game24:
    def __init__(self):
        pass

    def extract_numbers(self, expr) -> list:
        """Extracts numbers from an expression string."""
        curr_num = ''
        numbers = []
        for c in expr:
            if c.isdigit():
                curr_num += c
            elif curr_num:
                numbers.append(int(curr_num))
                curr_num = ''
        if curr_num:
            numbers.append(int(curr_num))
        return numbers

    def evaluate_result(self, result: str, case: List[int]) -> tuple:
        """
        Evaluates if the generated result for a 24 game case is correct.
        
        Args:
            result: The full text generated by the model
            case: The list of 4 input numbers
            
        Returns:
            tuple: (reward, correct) where reward is float and correct is int
        """
        try:
            # Extract the last line containing the expression
            output = result.split('assistant\n')[-1] if 'assistant\n' in result else result
            lines = output.strip().split('\n')
            
            # Find the last line with 'expression:'
            expr_line = None
            for line in reversed(lines):
                if 'expression:' in line:
                    expr_line = line
                    break
            
            if not expr_line:
                return 0.0, 0

            # Extract the expression
            expression = expr_line.split('expression:')[-1].strip()
            
            # Check if numbers match
            expr_numbers = sorted(self.extract_numbers(expression))
            input_numbers = sorted(case)
            if expr_numbers != input_numbers:
                return 0.0, 0

            # Safely evaluate the expression
            try:
                value = eval(expression, {"__builtins__": {}}, {})
                if abs(value - 24) < 1e-6:
                    return 1.0, 1
            except:
                return 0.0, 0
            
            return 0.0, 0

        except Exception as e:
            return 0.0, 0


class QwenAPI:
    """Qwen API calling class - using OpenAI style API"""
    def __init__(self, api_key: str, api_base: str = "https://dashscope.aliyuncs.com/compatible-mode/v1"):
        self.api_key = api_key
        self.api_base = api_base
        self.headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }
        # Import openai here if needed or handle AsyncOpenAI initialization
        # from openai import AsyncOpenAI
        # self.client = AsyncOpenAI(api_key=api_key, base_url=api_base)


    async def _generate_single(self, prompt: str, session: aiohttp.ClientSession) -> str:
        """Actual API call logic for a single prompt."""
        payload = {
            "model": "qwen-turbo", # Specified qwen-turbo
            "input": {
                "messages": [
                    {"role": "system", "content": "You are a helpful assistant."}, # Generic system prompt
                    {"role": "user", "content": prompt}
                ]
            },
            "parameters": {
                "temperature": 0.7, # Adjusted temperature
                 "max_tokens": 2048
            }
        }
        try:
            async with session.post(
                f"{self.api_base}/services/aigc/text-generation/generation", # Standard Qwen API endpoint
                headers=self.headers,
                json=payload
            ) as response:
                if response.status != 200:
                    error_text = await response.text()
                    # print(f"API call failed (status code: {response.status}): {error_text}")
                    raise Exception(f"API call failed (status code: {response.status}): {error_text}")
                json_response = await response.json()
                if "output" in json_response and "text" in json_response["output"]:
                    return json_response["output"]["text"]
                else:
                    # print(f"Unexpected API response format: {json_response}")
                    raise Exception(f"Unexpected API response format: {json_response}")
        except Exception as e:
            # print(f"Error during API call for prompt '{prompt[:50]}...': {e}")
            # import traceback
            # traceback.print_exc()
            raise

    async def generate_batch(self, prompts: List[str], batch_size: int = 5) -> List[str]:
        """Generates responses for a batch of prompts in parallel."""
        async with aiohttp.ClientSession() as session:
            tasks = [self._generate_single(prompt, session) for prompt in prompts]
            results = await asyncio.gather(*tasks, return_exceptions=True)
            return results


async def evaluate_prompt_performance(
    game24_prompt: str, 
    test_cases: List[List[int]],
    api_key: str,
    batch_size: int = 5
) -> float:
    """
    Evaluates the performance of a 24-game prompt.

    Args:
        game24_prompt: The prompt to instruct a model to solve 24-game.
        test_cases: A list of 24-game input numbers (e.g., [[1,2,3,4], [6,1,3,3]]).
        api_key: The API key for Qwen.
        batch_size: Batch size for API calls.

    Returns:
        The accuracy of the prompt on the test cases.
    """
    qwen_api = QwenAPI(api_key=api_key)
    reward_model = SimpleRewardModel4Game24()

    prompts_to_api = []
    for case_numbers in test_cases:
        user_input = " ".join(str(x) for x in case_numbers)
        # The game24_prompt is the instruction for the LLM to generate solutions
        # The LLM we are calling here will try to solve the 24 game based on the game24_prompt
        # So, the prompt to Qwen should be the game24_prompt + the specific numbers
        full_prompt_for_qwen = f"{game24_prompt}\\n\\nInput: {user_input}"
        prompts_to_api.append(full_prompt_for_qwen)

    generated_texts = await qwen_api.generate_batch(prompts_to_api, batch_size=batch_size)

    correct_count = 0
    
    # Use ThreadPoolExecutor for parallel evaluation of results
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
        eval_futures = []
        for i, numbers in enumerate(test_cases):
            generated_text = generated_texts[i]
            if isinstance(generated_text, Exception):
                # print(f"Error generating text for case {numbers}: {generated_text}")
                results_for_this_case = (0.0,0) # Count as incorrect if API call failed
            else:
                # Submit evaluation to thread pool
                future = executor.submit(reward_model.evaluate_result, generated_text, numbers)
                eval_futures.append(future)
        
        for future in eval_futures:
            try:
                _, correct = future.result() # result() will block until the future is complete
                if correct:
                    correct_count += 1
            except Exception as e:
                # print(f"Error evaluating result: {e}")
                # Count as incorrect if evaluation failed
                pass


    if not test_cases:
        return 0.0
    accuracy = correct_count / len(test_cases)
    return accuracy

def compute_score_batched(data_sources: List[str], solution_strs: List[str], 
                         ground_truths: List[str], extra_infos: List[Dict] = None) -> List[float]:
    """
    Batch processes multiple 24-game solutions in parallel.
    
    Args:
        data_sources: List of data source identifiers (unused but kept for consistency)
        solution_strs: List of solution strings from the model
        ground_truths: List of ground truth strings (JSON strings containing 5 test cases each)
        extra_infos: Additional information (unused but kept for consistency)
    
    Returns:
        List of scores (float) for each solution
    """
    reward_model = SimpleRewardModel4Game24()
    
    def evaluate_single_solution(solution_str: str, ground_truth_str: str) -> float:
        try:
            # Parse the ground truth JSON string to get the 5 test cases
            test_cases = json.loads(ground_truth_str)
            if not isinstance(test_cases, list) or len(test_cases) != 5:
                return 0.0
            
            # For each test case in the ground truth
            correct_count = 0
            for test_case in test_cases:
                if not isinstance(test_case, list) or len(test_case) != 4:
                    continue
                
                # Evaluate the solution against this test case
                _, correct = reward_model.evaluate_result(solution_str, test_case)
                if correct:
                    correct_count += 1
            
            # Return accuracy across all test cases
            return correct_count / len(test_cases)
            
        except Exception as e:
            return 0.0
    
    # Use ThreadPoolExecutor for parallel processing
    with ThreadPoolExecutor(max_workers=os.cpu_count()) as executor:
        # Submit all evaluation tasks
        futures = [
            executor.submit(evaluate_single_solution, solution_str, ground_truth)
            for solution_str, ground_truth in zip(solution_strs, ground_truths)
        ]
        
        # Collect results
        scores = [future.result() for future in futures]
    
    return scores

if __name__ == '__main__':
    # Example Usage:
    api_key_env = os.getenv("DASHSCOPE_API_KEY")
    if not api_key_env:
        raise ValueError("Please set the DASHSCOPE_API_KEY environment variable.")

    # This is the prompt we are evaluating. It's a meta-prompt.
    # It instructs another LLM (Qwen-Turbo in this case) on HOW to solve 24 game.
    example_game24_system_prompt = (
        "You are an expert in the 24 game. "
        "Given four numbers, find a way to combine them using addition, subtraction, multiplication, or division to reach the target number 24. "
        "Each number must be used exactly once. Parentheses can be used to control the order of operations. "
        "Provide a step-by-step reasoning of how you found the solution. "
        "On the last line, clearly state 'reach 24! expression: ' followed by the mathematical expression."
        "For example, if the input is '10 1 12 3', your final line should be 'reach 24! expression: ((12 + 3) + (10 - 1))'."
        "If no solution is possible, state 'No solution found.'"
    )

    # Load example test cases
    # In a real scenario, these might come from a file or be generated
    # For the dataset generation, these will be fixed 5 cases.
    try:
        with open("game24_test_cases.json", "r") as f:
            sample_test_cases = json.load(f) # Expecting a list of lists, e.g., [[1,2,3,4], ...]
    except FileNotFoundError:
        print("Error: game24_test_cases.json not found. Please create it with a list of test cases.")
        print("Example: [[1,2,3,4],[6,1,3,3],[8,8,3,2],[4,9,6,1],[7,7,3,1]]")
        sample_test_cases = [] # Fallback to empty if file not found for main guard

    if sample_test_cases:
        print(f"Evaluating prompt: '{example_game24_system_prompt[:100]}...'")
        start_time = time.time()
        accuracy = asyncio.run(evaluate_prompt_performance(
            game24_prompt=example_game24_system_prompt,
            test_cases=sample_test_cases, # Using the 5 fixed cases
            api_key=api_key_env,
            batch_size=5 # Match number of test cases for simplicity here
        ))
        end_time = time.time()
        print(f"Accuracy of the prompt: {accuracy*100:.2f}%")
        print(f"Evaluation took: {end_time - start_time:.2f} seconds")
    else:
        print("No test cases loaded, skipping example evaluation.")

    # Example usage of the new batched function
    example_solutions = [
        "Let me solve this step by step:\n1. First, I'll multiply 4 and 6: 4 * 6 = 24\n2. Done!\nexpression: 4 * 6",
        "No solution found."
    ]
    
    example_ground_truths = [
        json.dumps([[4, 6, 1, 1], [2, 3, 4, 5], [6, 6, 6, 6], [1, 2, 3, 4], [8, 8, 3, 1]]),
        json.dumps([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4], [5, 5, 5, 5]])
    ]
    
    scores = compute_score_batched(
        data_sources=["test"] * len(example_solutions),
        solution_strs=example_solutions,
        ground_truths=example_ground_truths,
        extra_infos=[{}] * len(example_solutions)
    )
    
    print("Example scores:", scores) 