# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
# 这是运行ScoreFlow/MetaGPT所需的最简化的配置。
# 将其保存为 config2.yaml 文件并放在您的项目根目录下。

# 模型列表: https://bailian.console.aliyun.com/?tab=doc#/doc/?type=model&url=https%3A%2F%2Fhelp.aliyun.com%2Fdocument_detail%2F2840914.html&renderType=iframe


#ALIBABA——IDEALAB
llm:
  # api_type 必须是 "openai"，因为您使用的是兼容OpenAI的接口。
  api_type: "openai"
  
  # 您的模型名称
  model: "qwen-turbo"
  
  # 您的API-Key
  api_key: "956c41bd0f31beaf68b871d4987af4bb"

  # 您的请求地址
  base_url: "https://idealab.alibaba-inc.com/api/openai/v1"


# 来自qzh哥哥
# llm:
#   # api_type 必须是 "openai"，因为您使用的是兼容OpenAI的接口。
#   api_type: "openai"
  
#   # 您的模型名称
#   model: "qwen-turbo"
  
#   # 您的API-Key
#   api_key: "sk-2df74af0570a42059c10a3f24de1b9df"

#   # 您的请求地址
#   base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"