# common/operator_an.py

from typing import Any, Dict, List, Union
from pydantic import BaseModel, Field

# 注意：`Summarize` 算子将复用 `GenerateOp`，因为它也只返回一个单一的文本块，
# 所以我们不需要为它定义一个独立的Pydantic模型。

class GenerateOp(BaseModel):
    """
    一个通用的、非结构化的文本响应模型。
    用于 `Generate` 和 `Summarize` 这类返回单一文本块的算子。
    """
    response: str = Field(
        ...,  # 设为必需字段，因为这是算子的唯一产出
        description="A generic, unstructured text response generated by the LLM."
    )

# class ExtractOp(BaseModel):
#     """
#     `Extract` 算子的结构化输出。
#     强制LLM返回一个可解析的JSON对象(在Python中表现为字典)。
#     """
#     extracted_data: Dict[str, Any] = Field(
#         ...,  # 设为必需字段
#         description="A JSON object (dictionary) containing the data extracted from the context based on the instruction."
#     )

class ReviseOp(BaseModel):
    """
    `Revise` 算子的结构化输出。
    包含思考过程和修订后的最终文本。
    """
    thought: str = Field(
        ..., 
        description="A step-by-step explanation of the revisions made and the reasoning behind them."
    )
    revised_context: str = Field(
        ...,
        description="The final, revised version of the input context."
    )

class EnsembleOp(BaseModel):
    """
    `Ensemble` 算子的结构化输出。
    包含决策或融合过程的思考，以及最终的结果。
    """
    thought: str = Field(
        ..., 
        description="The reasoning process for making the choice or synthesis, based on the provided instruction."
    )
    result: str = Field(
        ...,
        description="The final result of the ensemble operation. This could be one of the original options or a newly synthesized result."
    )

class FormatAnswerOp(BaseModel):
    """
    Ensures the final answer is extracted and structured correctly.
    This is a strict model; the 'final_answer' field is required.
    """
    final_answer: str = Field(
        ...,  # <-- 核心修改：设为必需字段
        description="The single, core final answer extracted from the raw workflow output."
    )