set +e

bash generate_LIMR_4_operator.sh
bash generate_DROP_4_operator.sh
bash generate_GSM8K_4_operator.sh
bash generate_HOTPOTQA_4_operator.sh
bash generate_MBPP_4_operator.sh
bash generate_HUMANEVAL_4_operator.sh

bash generate_DROP_6_operator.sh
bash generate_GSM8K_6_program.sh
bash generate_HOTPOTQA_6_operator.sh
bash generate_LIMR_6_operator.sh
bash generate_MBPP_6_operator.sh
bash generate_HUMANEVAL_6_operator.sh

bash generate_GSM8K_5_program.sh